// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadNavigateParams = { threadId: string,
/**
 * Existing turn id to make active. Omit or pass null to navigate to the root.
 */
targetTurnId?: string | null, };
